---
title: "PSYCH 251 Project Proposal"
author: "Mufan Luo"
date: "10/7/2017"
output: html_document
includes:
   in_header: header.tex
   before_body: doc_prefix.tex
   after_body: doc_suffix.tex
---

# Project Proposal 
## Rationale
For the final project in *PSYCH251*, I choose to replicate an experiment documented in Nekmat and colleagues (2015). My choice of experiment largely depends on my personal research interests and the statistic analysis methods that will be used in my future research. First, my research interests include online credibility, with a specific focus on the effects of social media affordances on believability and deception detections. For example, a current project aims to examine how relational closeness and social endorsement can influence people’s judgments of the news veracity on Facebook. **Nekmat, Gower, Zhou, and Metzger (2015)** employed an experiment to investigate the effects of message source (personal: friends, family, vs. impersonal: organization) on individuals’ willingness to engage in connective-type collective activities on social media (e.g., commenting). In particular, they included a key mediator---cognitive elaboration, and several moderators (e.g., perceived source credibility), which all had significant influence on online engagement. Their experiment is a good reference to my research, especially regarding the way they controlled relational closeness of the message source. Second, in order to test their hypotheses, the study run both moderation and mediation analyses which are of great importance in examining online mechanisms behind online information processing and/ or interpersonal processing. 

## Procedure
In order to replicate this experiment, I will need to recruit at least 200 participants on MTurk (the original sample size was 208). The experiment will be a one-way between-subject design where participants are randomly assigned to two conditions (personal source vs. organizational source). I may follow the same message stimuli used in the original work, which concerns a campaign against the University removing the Quad to build classrooms and offices. Participants will be either told that the post comes from 1) a member of their close personal network, or from 2) an organizational source. Then, according to Nekmat et al., participants in the personal condition will need to additional information about one of their close friends on social media, so as to simulate a real message reading scenario. Manipulation check will be performed regarding the perceived closeness of the source. In addition, participants will answer a couple of more questions regarding their willingness to engage in online collective activities, cognitive elaboration, perceived source credibility, personal issue involvement, attitude toward activism, and etc. 

## Challenges
The main challenges will lie in the different samples used in the replication experiment. The original experiment recruited college students from a university. Therefore, the message used in the experiment about removing the quad was highly relevant to the participants. However, the recruitment process of my replication work will be done on MTurk where people may not have common ground on a particular public issue. Thus, I may need to create a different version message stimuli. Alternatively, I may also rely on a student sample by recruiting 200 Stanford students and make the message relevant to a Stanford-related issue. Second, with respect to data analysis, the study employed an SPSS-installed macro, PROCESS (Hayes, 2013), a commonly used statistical package to test moderated mediation. To replicate the analysis in R, I may need to explore and learn the specific programming methods. However, I believe it will be an excellent learning process. 

